version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    platform: linux/amd64
    environment:
      - REDIS_HOSTS=local:redis:6379

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "7135:7135"

  postgres:
    image: postgres:15
    restart: always
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "3001:3001"
    depends_on:
      - postgres
